language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r crawler-web * # 현재 위치의 모든 파일을 해당이름으로 압축
  - mkdir -p deploy
  - mv crawler-web.zip deploy/crawler-web.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: crawler-springboot-build # S3 버킷
    region: ap-northeast-2
    cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait_until_deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: crawler-springboot-build
    key: crawler-web.zip
    bundle_type: zip
    application: crawler-webservice #codedeploy 웹 어플리케이션 이름
    region: ap-northeast-2
    wait_until_deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - sasca37@naver.com